### PR TITLE
Produce Reach, a remote I/O board for capturing sensor data.

### PR DESCRIPTION
**Pull request by tcr**
[Rendered](https://github.com/tessel/rfcs/blob/tcr-reach/0000-reach.md)

### CODE REVIEW

**Comment by tcr** [comment]
@jiahuang gave this feedback:

> battery/power req:
> - lipo (so must operate off of 3.3V). Lipos are longer lasting & easier to use than AA/AAA battery packs
> - usb powered ext battery (probably even more ubiquitous than lipos now due to cellphones)
> 
> so 3.3Vin & 5Vin
> 
> Programming:
> - might also be able to be programmed by being wired up to Tessel over uart

**Comment by rwaldron** [comment]
> might also be able to be programmed by being wired up to Tessel over uart

Yes! This is something I told @reconbot I wanted to do: plug the Reach into a Tessel to program and/or pair it.

**Comment by tcr** [comment]
@rwaldron Yeah, while I expect OTA will be the common mode of programming Reach, it still may be the case that users will use multiple programming modes over the lifetime of their Reach network; we should specify exactly how we want these programming mechanisms to work.

The current design has only one 10-pin female I/O port. Would you forsee a two-pin port being exposed to wire the UART to Tessel, or a full 10-pin male port to plug into Tessel? (And would that port have any additional uses?) It would be cool to also do pairing in this fashion, but we'd have to justify having an entire port just for the good UX.

**Comment by tcr** [comment]
@HipsterBrown One thing I realized is that it will be common for us to use Tessel simultaneously as an AP and a Station (wifi client). Do we currently use different `wifi-iface`s for the `t2 ap` support? I think we have two antennas and can use them simultaneously.

**Comment by HipsterBrown** [comment]
@tcr Yes, we use different wifi interfaces for `ap` and `wifi` so they can be used simultaneously.

**Comment by Frijol** [comment]
This PR should include adding the Reach RFC to the table of RFCs in the readme

**Comment by tcr** [comment]
Closing this for now. We'll re-merge if we reach a stable Reach RFC in the http://github.com/tessel/reach-wg working group.

**Pull request closed without merging**
